# Generated by Django 3.1.4 on 2021-01-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='steamID',
            field=models.BigIntegerField(unique=True),
        ),
    ]
