# Generated by Django 3.1.4 on 2021-06-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210520_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='user_name',
            new_name='userName',
        ),
    ]
