# Generated by Django 3.1.4 on 2021-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ismaincampaing', models.BooleanField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
