# Generated by Django 3.1.4 on 2021-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='missions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofmission', models.TextField()),
                ('missionName', models.TextField()),
                ('briefing', models.TextField()),
                ('solts', models.TextField()),
            ],
        ),
    ]
