# Generated by Django 3.1.4 on 2021-04-23 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0003_missions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='missions',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
