# Generated by Django 3.1.4 on 2021-05-05 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Missions', '0004_missions_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missions',
            old_name='solts',
            new_name='maxsolts',
        ),
        migrations.AddField(
            model_name='missions',
            name='joined',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
