# Generated by Django 3.1.4 on 2021-05-05 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Missions', '0005_auto_20210505_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missions',
            name='joined',
        ),
        migrations.AddField(
            model_name='missions',
            name='joined',
            field=models.ManyToManyField(null=True, related_name='joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
