# Generated by Django 3.1.4 on 2021-05-10 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Missions', '0006_auto_20210505_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missions',
            name='joined',
            field=models.ManyToManyField(related_name='joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
