# Generated by Django 3.1.4 on 2021-05-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0007_auto_20210510_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='missions',
            name='isfinish',
            field=models.BooleanField(default=False),
        ),
    ]
