# Generated by Django 3.1.4 on 2021-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.TextField(default=0)),
                ('killed', models.TextField(default=0)),
                ('distance', models.TextField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hitLocation', models.TextField()),
                ('typeOfHeal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='shootsfired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.TextField()),
                ('muzzle', models.TextField()),
                ('mode', models.TextField()),
                ('ammo', models.TextField()),
                ('magazine', models.TextField()),
                ('projectile', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='unconscious',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('createdat', models.DateTimeField()),
                ('updateat', models.DateTimeField()),
            ],
        ),
    ]
