# Generated by Django 3.1.4 on 2021-01-28 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='healed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healed', to=settings.AUTH_USER_MODEL, to_field='steamID'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='healer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healer', to=settings.AUTH_USER_MODEL, to_field='steamID'),
        ),
    ]
