# Generated by Django 3.1.4 on 2021-01-26 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kills',
            name='killer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medic',
            name='healer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shootsfired',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unconscious',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
