# Generated by Django 3.1.4 on 2021-02-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Arma', '0001_initial'),
        ('Missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unconscious',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_unconscious', to='Missions.missions'),
        ),
    ]
