# Generated by Django 3.1.4 on 2021-01-28 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arma', '0002_auto_20210128_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kills',
            name='killer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killer', to=settings.AUTH_USER_MODEL, to_field='steamID'),
        ),
        migrations.AlterField(
            model_name='shootsfired',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to=settings.AUTH_USER_MODEL, to_field='steamID'),
        ),
        migrations.AlterField(
            model_name='unconscious',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Uncoscious', to=settings.AUTH_USER_MODEL, to_field='steamID'),
        ),
    ]
