# Generated by Django 3.1.4 on 2021-01-14 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arma', '0002_auto_20210114_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kills',
            name='state',
        ),
        migrations.AddField(
            model_name='kills',
            name='distance',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='kills',
            name='killed',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='kills',
            name='killer',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='kills',
            name='weapon',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='kills',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shootsfired',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unconscious',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healer', models.BooleanField()),
                ('healed', models.TextField()),
                ('hitLocation', models.TextField()),
                ('typeOfHeal', models.TextField()),
                ('createdat', models.DateTimeField()),
                ('updateat', models.DateTimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
