# Generated by Django 3.1.4 on 2021-01-26 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        ('Arma', '0002_auto_20210126_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kills',
            name='killer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.info'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='healer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medic', to='Profile.info'),
        ),
        migrations.AlterField(
            model_name='shootsfired',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.info'),
        ),
        migrations.AlterField(
            model_name='unconscious',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.info'),
        ),
    ]
