# Generated by Django 3.1.4 on 2021-02-25 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Missions', '0002_missions_campaign'),
        ('Arma', '0002_unconscious_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='unconscious',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Uncoscious', to=settings.AUTH_USER_MODEL, to_field='steamID'),
        ),
        migrations.AddField(
            model_name='shootsfired',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='Missions.missions'),
        ),
        migrations.AddField(
            model_name='shootsfired',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to=settings.AUTH_USER_MODEL, to_field='steamID'),
        ),
        migrations.AddField(
            model_name='medic',
            name='healed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='healed', to=settings.AUTH_USER_MODEL, to_field='steamID'),
        ),
        migrations.AddField(
            model_name='medic',
            name='healer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='healer', to=settings.AUTH_USER_MODEL, to_field='steamID'),
        ),
        migrations.AddField(
            model_name='medic',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_medic', to='Missions.missions'),
        ),
        migrations.AddField(
            model_name='kills',
            name='killer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killer', to=settings.AUTH_USER_MODEL, to_field='steamID'),
        ),
        migrations.AddField(
            model_name='kills',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_kills', to='Missions.missions'),
        ),
    ]
