# Generated by Django 3.1.4 on 2021-01-14 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arma', '0003_auto_20210114_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shootsfired',
            name='unit',
        ),
        migrations.AlterField(
            model_name='shootsfired',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
