# Generated by Django 3.1.4 on 2021-01-14 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arma', '0004_auto_20210114_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shootsfired',
            old_name='vehicle',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='kills',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='medic',
            name='unit',
        ),
        migrations.AlterField(
            model_name='kills',
            name='killer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medic',
            name='healer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
